apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql-chart.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  MYSQL_DATABASE: {{ .Values.config.MYSQL_DATABASE }}
  MYSQL_USER: {{ .Values.config.MYSQL_USER }}
  DB_HOST: "{{ include "mysql-chart.fullname" . }}"
