apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mysql-chart.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.hostPath }}
