apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-chart.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.secrets.MYSQL_PASSWORD | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.MYSQL_ROOT_PASSWORD | b64enc }}
